### ISSUE TITLE
Unable to connect the Kupo

### ISSUE THREAD

**Issue by vnfastweb** [midnight-ntwrk/partner-chain-deps-docker#13]
### What Git revision / release tag are you using?
docker image: cardanosolutions/kupo:v2.9.0  

### Describe what the problem is?
I am installing this tool 

the kupo container is running ok .  also no firewall and selinux are enabled 
here is the output of container list 
CONTAINER ID   IMAGE                                           COMMAND                  CREATED      STATUS                  PORTS                    NAMES
1025ac3cc2a6   cardanosolutions/kupo:v2.9.0   "/bin/kupo --ogmios-…"   4 days ago   Up 25 hours..   0.0.0.0:1442->1442/tcp   kupo

and here is the output of service port 
tcp        0      0 0.0.0.0:1442            0.0.0.0:*               LISTEN      2658506/docker-prox

but unable to connect the Kupo , here is the telnet result 
telnet localhost 1442
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by lupsya** [comment]
Hi, 
I think the problem is the port binding inside your container. The host ports are looking ok. 

Is the container listening on 0.0.0.0 or 127.0.0.1? I expect the service port you shared is from the host machine?  

But what do you see in the container?
`docker exec -it kupo netstat -tuln | grep 1442
`
If you see 127.0.0.1:1442, the kupo container will refuse the connection coming from the outside (only allows localhost connections)


You can modify the compose file and add these two lines with --host and 0.0.0.0 (see below)
```
kupo:
    image: cardanosolutions/kupo:v2.9.0
    container_name: kupo
    command:
      - --ogmios-host
      - ogmios  # Assuming 'ogmios' is the service name in your docker-compose network
      - --ogmios-port
      - "1337"
      - --workdir
      - /db
      - --match
      - "*"
      - --since
      - "origin"
      - --host
      - 0.0.0.0
```

Then recreate the container 
`docker compose up -d kupo`

And check the port again 
`docker exec -it kupo netstat -tuln | grep 1442
`
You should see this output: 
`tcp        0      0 0.0.0.0:1442            0.0.0.0:*               LISTEN`

Also you will be able to telnet to this port, or test it via netcat 
`nc -zv <yourIP> 1442`

I hope this helps.
